from vonage_utils.errors import VonageError


class MessagesError(VonageError):
    """Indicates an error when using the Vonage Verify API."""
