from vonage_utils.errors import VonageError


class VerifyError(VonageError):
    """Indicates an error when using the Vonage Verify API."""
